---
- name: create custom facts directory
  file:
    path: /etc/ansible/facts.d
    state: directory
  become: yes
  when: sssd_deploy_facts

- name: deploy custom facts
  copy:
    src: sssd.fact
    dest: /etc/ansible/facts.d/sssd.fact
    mode: 0755
  become: yes
  when: sssd_deploy_facts


- name: install SSSD
  package:
    name: "{{ sssd_packages }}"
    state: present
  become: yes

- name: deploy sssd.conf
  template:
    src: sssd.conf.j2
    dest: /etc/sssd/sssd.conf
    mode: 0600
  become: yes
  notify:
    - restart sssd


- name: install oddjobd
  package:
    name: "{{ sssd_oddjob_packages }}"
    state: present
  become: yes
  notify:
    - restart oddjobd
  when: sssd_oddjob_mkhomedir

- name: add pam_mkhomedir.so to /etc/pam.d/common-session
  lineinfile:
    path: /etc/pam.d/common-session
    line: session required  pam_mkhomedir.so skel=/etc/skel/ umask=0022
    insertafter: 'session\s+required\s+pam_unix.so'
  become: yes
  when: sssd_oddjob_mkhomedir and __sssd_debian


- name: run authconfig
  command: /usr/sbin/authconfig {{ sssd_authconfig | longoptions() }} --update
  become: yes
  when: __sssd_redhat

- name: run sss_obfuscate so ldap_default_authtok is not plaintext
  shell: echo {{ sssd_domains[item]['ldap_default_authtok'] }} | sudo sss_obfuscate -d {{ item }} -f /etc/sssd/sssd.conf -s
  become: yes
  register: had_to_sss_obfuscate
  with_items: "{{ sssd_domains }}"
  when: sssd_domains[item].ldap_default_authtok is defined

# will restart only once, even if multiple obfuscations happen
- name: did obfuscation at least once, so restarting sssd service
  debug: msg="Had to obfuscate, so doing restart of sssd service"
  when: had_to_sss_obfuscate.changed
  notify:
    - restart sssd

- name: Copy ldap_tls_cacert to host for use by sssd as well as ldapsearch
  copy:
    src: "{{ sssd_local_ldap_cert_dir }}/{{ sssd_domains[item]['ldap_tls_cacert'] | basename }}"
    dest: "{{ sssd_domains[item]['ldap_tls_cacert'] }}"
    owner: root
    group: root
    mode: 'u=rw,g=r,o=r'
  with_items: "{{ sssd_domains }}"
  when: sssd_domains[item].ldap_tls_cacert is defined

- name: ensure TLS_REQCERT is set for ldap utilities, this is global
  lineinfile:
    path: /etc/ldap/ldap.conf
    regexp: '^TLS_REQCERT\t'
    line: "TLS_REQCERT\t{{ sssd_domains[item]['ldap_tls_reqcert'] }}"
    insertafter: EOF
    state: present
  become: yes
  with_items: "{{ sssd_domains }}"
  when: sssd_domains[item].ldap_tls_reqcert is defined

- name: add ldap_tls_cacert to /etc/ldap/ldap.conf
  lineinfile:
    path: /etc/ldap/ldap.conf
    line: "TLS_CACERT\t{{ sssd_domains[item]['ldap_tls_cacert'] }}"
    insertafter: EOF
    state: present
  become: yes
  with_items: "{{ sssd_domains }}"
  when: sssd_domains[item].ldap_tls_cacert is defined

- name: start sssd
  service:
    name: sssd
    enabled: True
    state: started
  become: yes

- name: start oddjobd
  service:
    name: oddjobd
    enabled: True
    state: started
  become: yes
  when: sssd_oddjob_mkhomedir
